export const AuthActionTypes = {
    AUTHENTICATE_USER: 'AUTHENTICATE_USER',
    UPDATE_TOKEN: 'UPDATE_TOKEN',
    LOGOUT_USER: 'LOGOUT_USER'
}

export const GroupActionTypes = {
    FETCH_USER_GROUPS: 'FETCH_USER_GROUPS',
    SET_CURRENT_GROUP: 'SET_CURRENT_GROUP',
    SET_GROUP_MEMBERS: 'SET_GROUP_MEMBERS' 
}